project:
  type: website
  output-dir: docs

website:
  title: "Karim Badr"
  google-analytics: "G-KDNF6K6698"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: work.qmd
        text: abc

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



